# Generated by Django 5.2.15 on 2026-06-09 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_order_paid_at_order_payment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('stack', 'Stack'), ('blend', 'Blend')], default='blend', max_length=20)),
                ('image', models.ImageField(upload_to='stack_blends/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from the storefront.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the landing page (top 4 shown).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stack / blend',
                'verbose_name_plural': 'stacks & blends',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stack_blend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='admin_app.stackblend'),
        ),
    ]
